[build-system]
requires = ["setuptools", "wheel"]


[tool.versioneer]
VCS = "git"
style = "pep440-old"
versionfile_source = "flowlauncher/_version.py"
versionfile_build = "flowlauncher/_version.py"
tag_prefix = "v"
parentdir_prefix = "flowlauncher-"
