name: sdist

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  sdist:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine

      - name: Build sdist
        run: |
          python setup.py sdist bdist_wheel
          twine check --strict dist/*
          ls -l dist

      - name: Install from sdist
        run: |
          pip list
          python -m pip install dist/*.gz

      - name: Import flowlauncher
        run: |
          python -V
          python -c "from flowlauncher import __version__; print(__version__);"
          python -c "import pprint; from flowlauncher._version import get_versions; pprint.pprint(get_versions());"
          conda info
          conda list

      - name: Publish to TestPyPI
        if: ${{ github.event_name == 'push' }}
        uses: pypa/gh-action-pypi-publish@v1.8.7
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
          skip_existing: true
